version: "3"
services:
  react-app:
    build: ./client
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - mongo
    networks:
      - mern-app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local